// <auto-generated />
namespace CYKP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class CYKP17 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CYKP17));
        
        string IMigrationMetadata.Id
        {
            get { return "202004201732079_CYKP17"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
