// <auto-generated />
namespace CYKP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class CYKP20 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CYKP20));
        
        string IMigrationMetadata.Id
        {
            get { return "202006180744548_CYKP20"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
